services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    ports:
      - "127.0.0.1:9090:9090"
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "127.0.0.1:3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-data_catalog}
    networks:
      - app-network
    depends_on:
      - postgres_db

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    networks:
      - app-network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    ports:
      - "127.0.0.1:8082:8080"
    networks:
      - app-network

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres-exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_db:5432/${POSTGRES_DB}?sslmode=disable
    networks:
      - app-network
    depends_on:
      - postgres_db

  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    container_name: kafka-exporter
    command: ["--kafka.server=kafka:29092"]
    networks:
      - app-network
    depends_on:
      - kafka

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox-exporter
    volumes:
      - ./monitoring/prometheus/blackbox.yml:/etc/blackbox/blackbox.yml 
    networks:
      - app-network
    # (blackbox.yml precisa ser criado também)

  loadtest:
    image: locustio/locust:latest
    container_name: loadtest
    volumes:
      - ./load_test:/mnt/locust
    command: ["-f", "/mnt/locust/locustfile.py"]
    ports:
      - "127.0.0.1:8089:8089"
    networks:
      - app-network