-- Drop tables if they already exist to start fresh
DROP TABLE IF EXISTS "columns_quality_rules" CASCADE;
DROP TABLE IF EXISTS "quality_rules" CASCADE;
DROP TABLE IF EXISTS "ingestions_columns_metadata" CASCADE;
DROP TABLE IF EXISTS "ingestions_table_metadata" CASCADE;
DROP TABLE IF EXISTS "ingestions" CASCADE;
DROP TABLE IF EXISTS "origins" CASCADE;
DROP TABLE IF EXISTS "siglas" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "pii_types" CASCADE;
-- 1. Table: users
CREATE TABLE IF NOT EXISTS "users" (
	"user_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"email" VARCHAR(255),
	"full_name" VARCHAR(255),
	PRIMARY KEY("user_id")
);
-- 2. Table: siglas
CREATE TABLE IF NOT EXISTS "siglas" (
	"sigla_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255),
	"owner_id" INTEGER,
	PRIMARY KEY("sigla_id"),
	CONSTRAINT fk_siglas_owner FOREIGN KEY("owner_id") REFERENCES "users"("user_id") ON UPDATE NO ACTION ON DELETE
	SET NULL
);
-- 3. Table: ingestions
CREATE TABLE IF NOT EXISTS "ingestions" (
	"ingestion_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
	"sigla_id" INTEGER,
	"created_at" DATE,
	"status" VARCHAR(255),
	"should_be_approved_until" DATE,
	"created_by" INTEGER,
	"last_updated_by" INTEGER,
	"active_version" INTEGER,
	"last_operation" VARCHAR(255),
	PRIMARY KEY("ingestion_id"),
	CONSTRAINT fk_ingestions_sigla FOREIGN KEY("sigla_id") REFERENCES "siglas"("sigla_id") ON UPDATE NO ACTION ON DELETE
	SET NULL,
		CONSTRAINT fk_ingestions_created_by FOREIGN KEY("created_by") REFERENCES "users"("user_id") ON UPDATE NO ACTION ON DELETE
	SET NULL,
		CONSTRAINT fk_ingestions_last_updated_by FOREIGN KEY("last_updated_by") REFERENCES "users"("user_id") ON UPDATE NO ACTION ON DELETE
	SET NULL
);
-- 4. Table: origins
CREATE TABLE IF NOT EXISTS "origins" (
	"sys_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"sys_name" VARCHAR(255),
	"sys_table_name" VARCHAR(255),
	PRIMARY KEY("sys_id")
);
-- 5. Table: ingestions_table_metadata
CREATE TABLE IF NOT EXISTS "ingestions_table_metadata" (
	"ingestion_id" INTEGER NOT NULL,
	"version" INTEGER NOT NULL,
	"created_at" DATE,
	"is_active" BOOLEAN,
	"table_name" VARCHAR(255),
	"table_description" VARCHAR(255),
	"origin" INTEGER,
	"layer" VARCHAR(255),
	"origin_format" VARCHAR(255),
	"periodicity" VARCHAR(255),
	"ingestion_type" VARCHAR(255),
	"inicial_date_update" DATE,
	PRIMARY KEY ("ingestion_id", "version"),
	CONSTRAINT fk_table_metadata_ingestion FOREIGN KEY("ingestion_id") REFERENCES "ingestions"("ingestion_id") ON UPDATE NO ACTION ON DELETE CASCADE,
	CONSTRAINT fk_table_metadata_origin FOREIGN KEY("origin") REFERENCES "origins"("sys_id") ON UPDATE NO ACTION ON DELETE
	SET NULL
);
-- Add self-reference from ingestions to ingestions_table_metadata for active_version
ALTER TABLE "ingestions"
ADD CONSTRAINT fk_ingestions_active_version FOREIGN KEY("ingestion_id", "active_version") REFERENCES "ingestions_table_metadata"("ingestion_id", "version") ON UPDATE NO ACTION ON DELETE
SET NULL;
-- 6. Table: pii_types
CREATE TABLE IF NOT EXISTS "pii_types" (
	"pii_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"pii_name" VARCHAR(255),
	PRIMARY KEY("pii_id")
);
-- 7. Table: ingestions_columns_metadata
CREATE TABLE IF NOT EXISTS "ingestions_columns_metadata" (
	"ingestion_id" INTEGER NOT NULL,
	"version" INTEGER NOT NULL,
	"column_name" VARCHAR(255) NOT NULL,
	"column_description" VARCHAR(255),
	"data_type" VARCHAR(255),
	"pii" VARCHAR(255),
	"pii_id" INTEGER,
	"partition_column" VARCHAR(255),
	"quality_rules_ids" INTEGER,
	PRIMARY KEY("ingestion_id", "version", "column_name"),
	CONSTRAINT fk_columns_table_metadata FOREIGN KEY("ingestion_id", "version") REFERENCES "ingestions_table_metadata"("ingestion_id", "version") ON UPDATE NO ACTION ON DELETE CASCADE,
	CONSTRAINT fk_columns_pii FOREIGN KEY("pii_id") REFERENCES "pii_types"("pii_id") ON UPDATE NO ACTION ON DELETE
	SET NULL
);
-- 8. Table: quality_rules
CREATE TABLE IF NOT EXISTS "quality_rules" (
	"rule_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"rule_name" VARCHAR(255),
	PRIMARY KEY("rule_id")
);
-- 9. Table: columns_quality_rules
CREATE TABLE IF NOT EXISTS "columns_quality_rules" (
	"rule_id" INTEGER NOT NULL,
	"ingestion_id" INTEGER NOT NULL,
	"version_id" INTEGER NOT NULL,
	"column_name" VARCHAR(255) NOT NULL,
	PRIMARY KEY(
		"rule_id",
		"ingestion_id",
		"version_id",
		"column_name"
	),
	CONSTRAINT fk_quality_rules_rule FOREIGN KEY("rule_id") REFERENCES "quality_rules"("rule_id") ON UPDATE NO ACTION ON DELETE CASCADE,
	CONSTRAINT fk_quality_rules_column FOREIGN KEY("ingestion_id", "version_id", "column_name") REFERENCES "ingestions_columns_metadata"("ingestion_id", "version", "column_name") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Seed users
INSERT INTO "users" ("user_id", "email", "full_name")
VALUES (1, 'jsilva@empresa.com', 'jsilva'),
	(2, 'rsantana@empresa.com', 'rsantana'),
	(3, 'amoreira@empresa.com', 'amoreira'),
	(4, 'cgarcia@empresa.com', 'cgarcia') ON CONFLICT ("user_id") DO NOTHING;
-- Seed siglas
INSERT INTO "siglas" ("sigla_id", "name", "owner_id")
VALUES (1, 'MKTI - Marketing e Tecnologia', 1),
	(2, 'FIN - Financeiro', 2),
	(3, 'TI - Tecnologia da Informação', 1) ON CONFLICT ("sigla_id") DO NOTHING;
-- Seed origins
INSERT INTO "origins" ("sys_id", "sys_name", "sys_table_name")
VALUES (1, 'oracle', 'tabela_origem_1'),
	(2, 'mysql', 'tabela_origem_2'),
	(3, 'sqlserver', 'tabela_origem_3') ON CONFLICT ("sys_id") DO NOTHING;
-- Seed quality_rules
INSERT INTO "quality_rules" ("rule_id", "rule_name")
VALUES (1, 'VALIDA_NULOS'),
	(2, 'VALIDA_BANDEIRA_CARTAO'),
	(3, 'VALIDA_CPF'),
	(4, 'VALIDA_CNPJ'),
	(5, 'VALIDA_EMAIL'),
	(6, 'VALIDA_TELEFONE'),
	(7, 'VALIDA_CEP') ON CONFLICT ("rule_id") DO NOTHING;
-- Seed pii_types
INSERT INTO "pii_types" ("pii_id", "pii_name")
VALUES (1, 'N/A'),
	(2, 'CPF'),
	(3, 'CNPJ'),
	(4, 'Email'),
	(5, 'Telefone'),
	(6, 'Endereço'),
	(7, 'Nome'),
	(8, 'Data Nascimento'),
	(9, 'Outros') ON CONFLICT ("pii_id") DO NOTHING;